apiVersion: v2
name: app
description: A Helm chart for Node.js application with MySQL database
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: database
    version: 0.1.0
    repository: file://../database
